services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    ports:
      - "9870:9870"   # Web UI
      - "9000:9000"   # HDFS port
    environment:
      - CLUSTER_NAME=test-cluster
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CLUSTER_NAME=test-cluster
    volumes:
      - datanode-data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    depends_on:
      - namenode
    networks:
      - hadoop
    environment:
      - HDFS_URL=http://namenode:9870
      - HDFS_USER=root

volumes:
  namenode-data:
  datanode-data:

networks:
  hadoop:
    driver: bridge
